name: example
publish_to: none
description: An example usage for the eventified_generator package.
version: 1.0.0
homepage: https://github.com/aloisdeniel/eventified

environment:
  sdk: '>=3.4.0'

dependencies:
  eventified: 

dev_dependencies:
  build_runner: ^2.3.3
  lints: ^2.0.0
  test: ^1.16.0
  eventified_generator: 
    path: ../eventified_generator

dependency_overrides:
  eventified:
    path: ../eventified
