name: example
publish_to: none
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.3 <3.0.0'

dependencies:
  eventified: 

dev_dependencies:
  build_runner: ^2.3.3
  lints: ^2.0.0
  test: ^1.16.0
  eventified_generator: 
    path: ../eventified_generator

dependency_overrides:
  eventified:
    path: ../eventified