name: eventified_generator
description: Transform method calls to a stream of events.
version: 0.3.0
homepage: https://github.com/aloisdeniel/eventified

environment:
  sdk: '>=3.4.0 <4.0.0'
  
dependencies:
  eventified: ^0.1.0
  analyzer: '>=8.0.0 <9.0.0'
  build: '>=3.0.0 <4.0.0'
  source_gen: '>=3.0.0 <4.0.0'
  code_builder: ^4.4.0
  dart_style: '>=3.0.0 <4.0.0'
  recase: ^4.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dependency_overrides:
  eventified:
    path: ../eventified
