name: eventified_generator
description: Transform method calls to a stream of events.
version: 0.3.0
homepage: https://github.com/aloisdeniel/eventified

environment:
  sdk: '>=3.4.0 <4.0.0'
  
dependencies:
  eventified: ^0.1.0
  analyzer: '>=4.6.0 <6.0.0'
  build: ^2.3.1
  source_gen: ^1.2.7
  code_builder: ^4.4.0
  dart_style: ^2.2.5
  recase: ^4.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dependency_overrides:
  eventified:
    path: ../eventified
